In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statistics 
import scipy.stats as stats
from scipy.stats import ttest_ind

In [2]:
df=pd.read_csv('Sales_add.csv')
df

Month      Region      Manager  Sales_before_digital_add(in $)  \
0    Month-1  Region - A  Manager - A                          132921   
1    Month-2  Region - A  Manager - C                          149559   
2    Month-3  Region - B  Manager - A                          146278   
3    Month-4  Region - B  Manager - B                          152167   
4    Month-5  Region - C  Manager - B                          159525   
5    Month-6  Region - A  Manager - B                          137163   
6    Month-7  Region - C  Manager - C                          130625   
7    Month-8  Region - A  Manager - A                          131140   
8    Month-9  Region - B  Manager - C                          171259   
9   Month-10  Region - C  Manager - B                          141956   
10  Month-11  Region - B  Manager - C                          159339   
11  Month-12  Region - A  Manager - A                          178939   
12  Month-13  Region - B  Manager - A                          145062   
13  Month-14  Region - A  Manager - A                          151514   
14  Month-15  Region - C  Manager - A                          147463   
15  Month-16  Region - A  Manager - B                          177195   
16  Month-17  Region - A  Manager - C                          140862   
17  Month-18  Region - C  Manager - B                          167996   
18  Month-19  Region - B  Manager - A                          132135   
19  Month-20  Region - A  Manager - B                          152493   
20  Month-21  Region - B  Manager - A                          147425   
21  Month-22  Region - A  Manager - C                          130263   

    Sales_After_digital_add(in $)  
0                          270390  
1                          223334  
2                          244243  
3                          231808  
4                          258402  
5                          256948  
6                          222106  
7                          230637  
8                          226261  
9                          193735  
10                         203175  
11                         276279  
12                         205180  
13                         253131  
14                         229336  
15                         187305  
16                         234908  
17                         191517  
18                         227040  
19                         212579  
20                         263388  
21                         243020

# ● The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.


In [6]:
#H0:there is no increase in sales after stepping into digital marketing.
#H1:there is increase in sales after stepping into digital marketing.
alpha=0.05
t_value,p_value=stats.ttest_rel(df['Sales_After_digital_add(in $)'],df['Sales_before_digital_add(in $)'])
if p_value>alpha:
     print("accept H0")
else:
    print("reject H0")


reject H0


that means there is  increase in sales after stepping into digital marketing

# ● The company needs to check whether there is any dependency between the features “Region” and “Manager”.

In [8]:
# H0:there is no dependency between the features “Region” and “Manager”
#H1: there is  dependency between the features “Region” and “Manager”
df_table=pd.crosstab(df['Region'],df['Manager'])
print(df_table)

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1


In [9]:
observed_values=df_table.values
print('observed_values:-\n',observed_values)

observed_values:-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [10]:
val=stats.chi2_contingency(df_table)
val

(3.050566893424036,
 0.5493991051158094,
 4,
 array([[4.09090909, 3.18181818, 2.72727273],
        [2.86363636, 2.22727273, 1.90909091],
        [2.04545455, 1.59090909, 1.36363636]]))

In [11]:
expected_values=val[3]

In [12]:
no_of_rows=len(df_table.iloc[0:3,0])
no_of_columns=len(df_table.iloc[0,0:3])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of freedom:-",ddof)
alpha=0.05

Degree of freedom:- 4


In [13]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(observed_values,expected_values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print('chi-square statistic:-' ,chi_square_statistic)

chi-square statistic:- 2.921995464852608


In [14]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 9.487729036781154


In [15]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print("p-value:",p_value)
print('significance level:',alpha)
print('degree of freedom',ddof)

p-value: 0.5709629929220089
significance level: 0.05
degree of freedom 4


In [16]:
if chi_square_statistic>critical_value:
    print("reject H0")
else:
    print("accept H0")
#or
    
if p_value<=alpha:
     print("reject H0")
else:
    print("accept H0")


accept H0
accept H0


that means there is no dependency between the features “Region” and “Manager”